spring.application.name=memory-app
server.port=8081
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=mistral
spring.ai.ollama.embedding.model=mxbai-embed-large
spring.ai.ollama.chat.options.temperature=0.0
spring.ai.ollama.chat.options.maxTokens=200
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.datasource.url=jdbc:mariadb://localhost:3308/springai-vector
spring.datasource.username=root
spring.datasource.password=root1234

spring.ai.vectorstore.mariadb.initialize-schema=true
spring.ai.vectorstore.mariadb.distance-type=cosine
spring.ai.vectorstore.mariadb.dimensions=1024

#spring.ai.chat.memory.repository.jdbc.initialize-schema=always
